project:
  type: website
  output-dir: docs

website:
  title: "Zhanchao Yang - MUSA 5080 Portfolio"
  navbar:
    title: "Portfolio"
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Notes"
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
      - text: Assignments
        menu:
          - href: assignments/assignment_1/assignment1.qmd
            text: "Assignment 1: Census Data Exploration"
   
    right:
      - icon: github
        href: https://github.com/MUSA-5080-Fall-2025/portfolio-setup-zyang91


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
