project:
  type: website
  output-dir: docs

website:
  title: "Zhanchao Yang - MUSA 5080 Portfolio"
  navbar:
    title: "Portfolio"
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Notes"
        menu:
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
      - text: "Labs"
        menu:
           - href: labs/
             text: "All Labs"
           - href: labs/sample-lab.qmd
             text: "Sample Census Analysis"
    right:
      - icon: github
        href: https://github.com/MUSA-5080-Fall-2025/portfolio-setup-zyang91


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
